INSERT OR IGNORE INTO packages (name, description, version, license, repository) VALUES
  ('alexandria', 'A collection of portable public-domain utilities', '1.4', 'Public Domain', 'https://gitlab.common-lisp.net/alexandria/alexandria'),
  ('cl-ppcre', 'Portable Perl-compatible regular expressions', '2.1.2', 'BSD-2', 'https://github.com/edicl/cl-ppcre'),
  ('bordeaux-threads', 'Portable multithreading primitives', '0.9.4', 'MIT', 'https://github.com/sionescu/bordeaux-threads'),
  ('usocket', 'Universal socket library', '0.8.7', 'MIT', 'https://github.com/usocket/usocket'),
  ('dexador', 'Fast HTTP client', '0.9.15', 'MIT', 'https://github.com/fukamachi/dexador'),
  ('jonathan', 'High-performance JSON encoder/decoder', '0.1.0', 'MIT', 'https://github.com/Rudolph-Miller/jonathan'),
  ('lack', 'Minimal Clack-compatible web application interface', '0.2.0', 'MIT', 'https://github.com/fukamachi/lack'),
  ('ningle', 'Lightweight web framework', '0.3.0', 'MIT', 'https://github.com/fukamachi/ningle'),
  ('sxql', 'SQL generator from S-expressions', '0.1.0', 'BSD-3', 'https://github.com/fukamachi/sxql'),
  ('mito', 'ORM with migration support', '0.2.0', 'MIT', 'https://github.com/fukamachi/mito'),
  ('cl-async', 'Asynchronous I/O library', '0.6.1', 'MIT', 'https://github.com/orthecreedence/cl-async'),
  ('ironclad', 'Cryptographic toolkit', '0.59', 'MIT', 'https://github.com/sharplispers/ironclad'),
  ('lparallel', 'Parallel programming library', '2.8.4', 'BSD-3', 'https://github.com/lmj/lparallel'),
  ('trivia', 'Pattern matching for Common Lisp', '0.0.1', 'MIT', 'https://github.com/guicho271828/trivia'),
  ('str', 'Modern string manipulation library', '0.19', 'MIT', 'https://github.com/vindarel/cl-str'),
  ('log4cl', 'Logging framework', '1.1.4', 'Apache-2.0', 'https://github.com/sharplispers/log4cl'),
  ('fiveam', 'Regression testing framework', '1.4.2', 'BSD', 'https://github.com/lispci/fiveam'),
  ('parachute', 'Extensible testing framework', '1.5.0', 'zlib', 'https://github.com/Shinmera/parachute'),
  ('arrows', 'Threading macro implementations', '0.2.0', 'CC0', 'https://github.com/Harleqin/arrows'),
  ('serapeum', 'Utilities beyond Alexandria', '0.0.1', 'MIT', 'https://github.com/ruricolist/serapeum'),
  ('cl-json', 'JSON encoder/decoder', '0.7.0', 'MIT', 'https://github.com/sharplispers/cl-json'),
  ('hunchentoot', 'Web server written in Common Lisp', '1.3.0', 'BSD-2', 'https://github.com/edicl/hunchentoot'),
  ('closer-mop', 'Cross-implementation MOP compatibility', '1.0.0', 'MIT', 'https://github.com/pcostanza/closer-mop'),
  ('cffi', 'C foreign function interface', '0.24.1', 'MIT', 'https://github.com/cffi/cffi'),
  ('flexi-streams', 'Flexible bivalent streams', '1.0.19', 'BSD-2', 'https://github.com/edicl/flexi-streams');

-- Dependencies
INSERT OR IGNORE INTO dependencies (package_id, dependency_name) VALUES
  ((SELECT id FROM packages WHERE name='usocket'), 'bordeaux-threads'),
  ((SELECT id FROM packages WHERE name='dexador'), 'usocket'),
  ((SELECT id FROM packages WHERE name='dexador'), 'bordeaux-threads'),
  ((SELECT id FROM packages WHERE name='dexador'), 'cl-ppcre'),
  ((SELECT id FROM packages WHERE name='jonathan'), 'cl-ppcre'),
  ((SELECT id FROM packages WHERE name='lack'), 'alexandria'),
  ((SELECT id FROM packages WHERE name='lack'), 'bordeaux-threads'),
  ((SELECT id FROM packages WHERE name='ningle'), 'lack'),
  ((SELECT id FROM packages WHERE name='ningle'), 'alexandria'),
  ((SELECT id FROM packages WHERE name='ningle'), 'cl-ppcre'),
  ((SELECT id FROM packages WHERE name='sxql'), 'alexandria'),
  ((SELECT id FROM packages WHERE name='mito'), 'sxql'),
  ((SELECT id FROM packages WHERE name='mito'), 'alexandria'),
  ((SELECT id FROM packages WHERE name='mito'), 'closer-mop'),
  ((SELECT id FROM packages WHERE name='cl-async'), 'bordeaux-threads'),
  ((SELECT id FROM packages WHERE name='cl-async'), 'cffi'),
  ((SELECT id FROM packages WHERE name='ironclad'), 'bordeaux-threads'),
  ((SELECT id FROM packages WHERE name='lparallel'), 'bordeaux-threads'),
  ((SELECT id FROM packages WHERE name='lparallel'), 'alexandria'),
  ((SELECT id FROM packages WHERE name='trivia'), 'alexandria'),
  ((SELECT id FROM packages WHERE name='str'), 'cl-ppcre'),
  ((SELECT id FROM packages WHERE name='log4cl'), 'bordeaux-threads'),
  ((SELECT id FROM packages WHERE name='fiveam'), 'alexandria'),
  ((SELECT id FROM packages WHERE name='serapeum'), 'alexandria'),
  ((SELECT id FROM packages WHERE name='serapeum'), 'bordeaux-threads'),
  ((SELECT id FROM packages WHERE name='hunchentoot'), 'usocket'),
  ((SELECT id FROM packages WHERE name='hunchentoot'), 'bordeaux-threads'),
  ((SELECT id FROM packages WHERE name='hunchentoot'), 'cl-ppcre'),
  ((SELECT id FROM packages WHERE name='cffi'), 'bordeaux-threads'),
  ((SELECT id FROM packages WHERE name='cffi'), 'alexandria');
